services:
  emspo-fe-audit:
    container_name: emspo-fe-audit
    image: emspo/mspots_fe:dev3500
    init: true
    restart: always
    networks:
      - msponetaudit
    ports:
      - "0.0.0.0:3500:3000"

  emspo-be-audit:
    container_name: emspo-be-audit
    image: emspo/mspots_be:dev3500
    init: true
    env_file: dev3500.env
    volumes:
      - mspots_be_volume-audit:/var/www/mspo-ts-api/uploads/
    networks:
      - msponetaudit
      - supabase_default
    ports:
      - "0.0.0.0:3501:3003"
    restart: always
  emspo-be-2-audit:
    container_name: emspo_api_prod
    image: emspo/emspo_be_2:dev3500
    restart: unless-stopped
    env_file: dev3500.env
    environment:
      - NODE_ENV=production
    ports:
      - '3002:3002'
    networks:
      - msponetaudit
      - supabase_default
    healthcheck:
      test:
        [
            'CMD',
            'node',
            '-e',
            "require('http').get('http://localhost:${PORT:-3002}/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mspots_be_volume-audit:
    driver: local
    driver_opts:
      type: none
      device: /var/www/mspo-ts-api-audit/uploads/
      o: bind

networks:
  msponetaudit:
    driver: bridge
  supabase_default:
    name: supabase_default
    external: true
    driver: bridge
#    enable_ipv6: true
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.28.0.0/16"
#        - subnet: "2001:db8:1::/64"
