services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /var/lib/portainer
    #   o: bind
    # labels:
    #   - "com.docker.compose.project=portainer"
    #   - "com.docker.compose.service=portainer"
    #   - "com.docker.compose.oneoff=False"
    # networks:
    #   - portainer_network